import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Magic } from "magic-sdk";
import { ethers } from "ethers";
import { parseEther } from "ethers";
import React, { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const provider = new ethers.getDefaultProvider("goerli");

  const [magic, setMagic] = useState(null);
  const [account, setAccount] = useState("");
  // const provider = new ethers.getDefaultProvider("http://127.0.0.1:8545/");

  useEffect(() => {
    const m = new Magic("pk_live_1E208ADDCC61B99E", {
      network: "goerli",
    });
    setMagic(m);
  }, []);

  async function test() {
    try {
      const accounts = await magic.wallet.connectWithUI();
      console.log("THE ACCOUNT IS");
      console.log(accounts);
      setAccount(accounts[0]);
    } catch (err) {
      console.error(err);
      alert("Error connecting wallet. Please try again.");
    }
  }

  function handleSubmitSign() {
    document.getElementById("sign-btn").disabled = true;
    test().finally(() => {
      document.getElementById("sign-btn").disabled = false;
    });
  }

  async function handleSubmit() {
    try {
      const { walletType } = await magic.wallet.getInfo();

      if (walletType === "magic") {
        await magic.wallet.showUI(); // shows wallet widget
      }
    } catch {
      console.log("HEY Beautiful");
    }
  }

  async function sendTransaction() {
    // Set up signer with private key
    const privateKey =
      "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
    const signer = new ethers.Wallet(privateKey, provider);

    // Set up transaction parameters
    const txParams = {
      from: signer,
      to: account,
      value: parseEther("1000"),
      gasLimit: 1000000,
    };

    // Send transaction
    const tx = await signer.sendTransaction(txParams);
    console.log("Transaction hash:", tx.hash);
  }

  return (
    <>
      <script src="https://auth.magic.link/sdk"></script>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={handleSubmitSign} id="sign-btn">
        Sign In With Magic
      </button>
      <button onClick={handleSubmit}>Send Tran</button>
      <button onClick={sendTransaction}>Send money</button>

      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
